package org.mss.test;

//import org.junit.jupiter.api.Test;
//
//import javax.persistence.EntityManager;
//import javax.persistence.EntityManagerFactory;
//import javax.persistence.Persistence;

public class TestBench {

//    @Test
//    public void t() {
//        ,BOOT-INF/lib/animal-sniffer-annotations-1.14.jar
//        ,BOOT-INF/lib/annotations-4.1.1.4.jar
//        ,BOOT-INF/lib/api-common-1.8.1.jar
//        ,BOOT-INF/lib/auto-value-annotations-1.6.6.jar
//        ,BOOT-INF/lib/checker-compat-qual-2.5.2.jar
//        ,BOOT-INF/lib/commons-codec-1.15.jar
//        ,BOOT-INF/lib/commons-lang3-3.12.0.jar
//        ,BOOT-INF/lib/error_prone_annotations-2.3.2.jar
//        ,BOOT-INF/lib/firebase-admin-6.11.0.jar
//        ,BOOT-INF/lib/gax-1.48.1.jar
//        ,BOOT-INF/lib/gax-grpc-1.48.1.jar
//        ,BOOT-INF/lib/gax-httpjson-0.65.1.jar
//        ,BOOT-INF/lib/google-api-client-1.30.1.jar
//        ,BOOT-INF/lib/google-api-client-gson-1.30.1.jar
//        ,BOOT-INF/lib/google-api-services-storage-v1-rev20190624-1.30.1.jar
//        ,BOOT-INF/lib/google-auth-library-credentials-0.17.1.jar
//        ,BOOT-INF/lib/google-auth-library-oauth2-http-0.17.1.jar
//        ,BOOT-INF/lib/google-cloud-core-1.90.0.jar
//        ,BOOT-INF/lib/google-cloud-core-grpc-1.90.0.jar
//        ,BOOT-INF/lib/google-cloud-core-http-1.90.0.jar
//        ,BOOT-INF/lib/google-cloud-firestore-1.21.0.jar
//        ,BOOT-INF/lib/google-cloud-storage-1.91.0.jar
//        ,BOOT-INF/lib/google-http-client-1.30.1.jar
//        ,BOOT-INF/lib/google-http-client-appengine-1.31.0.jar
//        ,BOOT-INF/lib/google-http-client-gson-1.30.1.jar
//        ,BOOT-INF/lib/google-http-client-jackson2-1.30.1.jar
//        ,BOOT-INF/lib/google-oauth-client-1.30.1.jar
//        ,BOOT-INF/lib/grpc-alts-1.23.0.jar
//        ,BOOT-INF/lib/grpc-api-1.23.0.jar
//        ,BOOT-INF/lib/grpc-auth-1.23.0.jar
//        ,BOOT-INF/lib/grpc-context-1.19.0.jar
//        ,BOOT-INF/lib/grpc-core-1.23.0.jar
//        ,BOOT-INF/lib/grpc-grpclb-1.23.0.jar
//        ,BOOT-INF/lib/grpc-netty-shaded-1.23.0.jar
//        ,BOOT-INF/lib/grpc-protobuf-1.23.0.jar
//        ,BOOT-INF/lib/grpc-protobuf-lite-1.23.0.jar
//        ,BOOT-INF/lib/grpc-stub-1.23.0.jar
//        ,BOOT-INF/lib/gson-2.8.7.jar
//        ,BOOT-INF/lib/guava-26.0-android.jar
//        ,BOOT-INF/lib/httpclient-4.5.13.jar
//        ,BOOT-INF/lib/httpcore-4.4.14.jar
//        ,BOOT-INF/lib/j2objc-annotations-1.3.jar
//        ,BOOT-INF/lib/jackson-annotations-2.12.4.jar
//        ,BOOT-INF/lib/jackson-core-2.12.4.jar
//        ,BOOT-INF/lib/jackson-databind-2.12.4.jar
//        ,BOOT-INF/lib/jackson-datatype-jdk8-2.12.4.jar
//        ,BOOT-INF/lib/jackson-datatype-jsr310-2.12.4.jar
//        ,BOOT-INF/lib/jackson-module-parameter-names-2.12.4.jar
//        ,BOOT-INF/lib/jakarta.annotation-api-1.3.5.jar
//        ,BOOT-INF/lib/jakarta.ejb-api-3.2.6.jar
//        ,BOOT-INF/lib/jakarta.el-api-3.0.3.jar
//        ,BOOT-INF/lib/jakarta.enterprise.cdi-api-2.0.2.jar
//        ,BOOT-INF/lib/jakarta.inject-api-1.0.jar
//        ,BOOT-INF/lib/jakarta.interceptor-api-1.2.5.jar
//        ,BOOT-INF/lib/jakarta.transaction-api-1.3.3.jar
//        ,BOOT-INF/lib/javax.annotation-api-1.3.2.jar
//        ,BOOT-INF/lib/jsr305-3.0.2.jar
//        ,BOOT-INF/lib/jul-to-slf4j-1.7.32.jar
//        ,BOOT-INF/lib/log4j-api-2.14.1.jar
//        ,BOOT-INF/lib/log4j-to-slf4j-2.14.1.jar
//        ,BOOT-INF/lib/logback-classic-1.2.4.jar
//        ,BOOT-INF/lib/logback-core-1.2.4.jar
//        ,BOOT-INF/lib/netty-buffer-4.1.66.Final.jar
//        ,BOOT-INF/lib/netty-codec-4.1.66.Final.jar
//        ,BOOT-INF/lib/netty-codec-http-4.1.66.Final.jar
//        ,BOOT-INF/lib/netty-common-4.1.66.Final.jar
//        ,BOOT-INF/lib/netty-handler-4.1.66.Final.jar
//        ,BOOT-INF/lib/netty-resolver-4.1.66.Final.jar
//        ,BOOT-INF/lib/netty-transport-4.1.66.Final.jar
//        ,BOOT-INF/lib/opencensus-api-0.21.0.jar
//        ,BOOT-INF/lib/opencensus-contrib-grpc-metrics-0.21.0.jar
//        ,BOOT-INF/lib/opencensus-contrib-grpc-util-0.23.0.jar
//        ,BOOT-INF/lib/opencensus-contrib-http-util-0.21.0.jar
//        ,BOOT-INF/lib/org.osgi.service.cdi-1.0.0.jar
//        ,BOOT-INF/lib/osgi.cmpn-7.0.0.jar
//        ,BOOT-INF/lib/osgi.core-7.0.0.jar
//        ,BOOT-INF/lib/perfmark-api-0.17.0.jar
//        ,BOOT-INF/lib/protobuf-java-3.9.1.jar
//        ,BOOT-INF/lib/protobuf-java-util-3.9.1.jar
//        ,BOOT-INF/lib/proto-google-cloud-firestore-admin-v1-1.21.0.jar
//        ,BOOT-INF/lib/proto-google-cloud-firestore-v1-1.21.0.jar
//        ,BOOT-INF/lib/proto-google-cloud-firestore-v1beta1-0.74.0.jar
//        ,BOOT-INF/lib/proto-google-common-protos-1.16.0.jar
//        ,BOOT-INF/lib/proto-google-iam-v1-0.12.0.jar
//        ,BOOT-INF/lib/slf4j-api-1.7.32.jar
//        ,BOOT-INF/lib/snakeyaml-1.28.jar
//        ,BOOT-INF/lib/spring-aop-5.3.9.jar
//        ,BOOT-INF/lib/spring-beans-5.3.9.jar
//        ,BOOT-INF/lib/spring-boot-2.5.3.jar
//        ,BOOT-INF/lib/spring-boot-autoconfigure-2.5.3.jar
//        ,BOOT-INF/lib/spring-boot-jarmode-layertools-2.5.3.jar
//        ,BOOT-INF/lib/spring-context-5.3.9.jar
//        ,BOOT-INF/lib/spring-core-5.3.9.jar
//        ,BOOT-INF/lib/spring-expression-5.3.9.jar
//        ,BOOT-INF/lib/spring-jcl-5.3.9.jar
//        ,BOOT-INF/lib/spring-package-api-1.0.jar
//        ,BOOT-INF/lib/spring-web-5.3.9.jar
//        ,BOOT-INF/lib/spring-webmvc-5.3.9.jar
//        ,BOOT-INF/lib/threetenbp-1.3.3.jar
//        ,BOOT-INF/lib/tomcat-embed-core-9.0.50.jar
//        ,BOOT-INF/lib/tomcat-embed-el-9.0.50.jar
//        ,BOOT-INF/lib/tomcat-embed-websocket-9.0.50.jar
//    }
}
